# Generated by Django 5.1.7 on 2025-05-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
