# Generated by Django 5.1.7 on 2025-05-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
